---
- name: Install Git
  ansible.builtin.apt:
    name: git
    state: present
  register: tools_git_install
  until: tools_git_install is succeeded
  retries: 3
  delay: 5

- name: Configure Git
  ansible.builtin.copy:
    dest: /root/.gitconfig
    content: |
      [init]
          defaultBranch = master
      [core]
          editor = vim
      [pull]
          rebase = false
    mode: '0644'

- name: Download GitHub CLI GPG key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'
  register: tools_gh_key_download
  until: tools_gh_key_download is succeeded
  retries: 3
  delay: 5

- name: Add GitHub CLI repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_facts['architecture'] | regex_replace('x86_64', 'amd64') }}
      signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg]
      https://cli.github.com/packages stable main
    filename: github-cli
    state: present
  register: tools_gh_repo_add
  until: tools_gh_repo_add is succeeded
  retries: 3
  delay: 5

- name: Install GitHub CLI
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
  register: tools_gh_install
  until: tools_gh_install is succeeded
  retries: 3
  delay: 5
